[2023-07-05 23:05:27,617] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:05:24.092370+00:00 [queued]>
[2023-07-05 23:05:27,626] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:05:24.092370+00:00 [queued]>
[2023-07-05 23:05:27,627] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:05:27,627] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-05 23:05:27,628] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:05:27,639] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): email> on 2023-07-05 23:05:24.092370+00:00
[2023-07-05 23:05:27,645] {standard_task_runner.py:52} INFO - Started process 194 to run task
[2023-07-05 23:05:27,651] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'email', 'manual__2023-07-05T23:05:24.092370+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmp6zdf1fl_', '--error-file', '/tmp/tmp7awwymon']
[2023-07-05 23:05:27,653] {standard_task_runner.py:80} INFO - Job 64: Subtask email
[2023-07-05 23:05:27,722] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.email manual__2023-07-05T23:05:24.092370+00:00 [running]> on host 0808ffb1fb61
[2023-07-05 23:05:27,761] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-05 23:05:27,800] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=email
AIRFLOW_CTX_EXECUTION_DATE=2023-07-05T23:05:24.092370+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-05T23:05:24.092370+00:00
[2023-07-05 23:05:27,817] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 1603, in _ensure_numeric
    x = float(x)
ValueError: could not convert string to float: '13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0Vino13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 1607, in _ensure_numeric
    x = complex(x)
ValueError: complex() arg is a malformed string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/API_ETL.py", line 87, in enviar
    vino_mean = dataframe['Vino'].mean()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 10751, in mean
    return NDFrame.mean(self, axis, skipna, level, numeric_only, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 10370, in mean
    "mean", nanops.nanmean, axis, skipna, level, numeric_only, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 10355, in _stat_function
    func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 4392, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 94, in _f
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 156, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 411, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 666, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 1610, in _ensure_numeric
    raise TypeError(f"Could not convert {x} to numeric") from err
TypeError: Could not convert 13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0Vino13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0 to numeric
[2023-07-05 23:05:27,835] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=API_ETL, task_id=email, execution_date=20230705T230524, start_date=20230705T230527, end_date=20230705T230527
[2023-07-05 23:05:27,856] {standard_task_runner.py:97} ERROR - Failed to execute job 64 for task email (Could not convert 13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0Vino13.012.011.012.012.015.011.011.012.013.014.014.015.013.014.013.014.017.014.013.012.015.017.019.018.016.016.014.015.020.014.014.014.014.015.017.015.014.014.013.014.020.013.014.014.016.016.018.017.016.015.015.014.019.016.014.014.015.016.018.0 to numeric; 194)
[2023-07-05 23:05:27,903] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-05 23:05:27,944] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
