[2023-06-14 14:50:22,478] {processor.py:153} INFO - Started process (PID=168) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:22,479] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:50:22,480] {logging_mixin.py:115} INFO - [2023-06-14 14:50:22,480] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:22,494] {logging_mixin.py:115} INFO - [2023-06-14 14:50:22,493] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:50:22,495] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:22,518] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 14:50:32,596] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:32,598] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:50:32,600] {logging_mixin.py:115} INFO - [2023-06-14 14:50:32,600] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:32,613] {logging_mixin.py:115} INFO - [2023-06-14 14:50:32,611] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:50:32,614] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:32,639] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.049 seconds
[2023-06-14 14:50:42,733] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:42,734] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:50:42,736] {logging_mixin.py:115} INFO - [2023-06-14 14:50:42,736] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:42,746] {logging_mixin.py:115} INFO - [2023-06-14 14:50:42,744] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:50:42,747] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:42,770] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:50:52,864] {processor.py:153} INFO - Started process (PID=183) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:52,865] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:50:52,867] {logging_mixin.py:115} INFO - [2023-06-14 14:50:52,867] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:52,877] {logging_mixin.py:115} INFO - [2023-06-14 14:50:52,875] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:50:52,878] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:50:52,902] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 14:51:02,990] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:02,992] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:02,993] {logging_mixin.py:115} INFO - [2023-06-14 14:51:02,993] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:03,003] {logging_mixin.py:115} INFO - [2023-06-14 14:51:03,001] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:03,004] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:03,028] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:51:13,111] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:13,112] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:13,113] {logging_mixin.py:115} INFO - [2023-06-14 14:51:13,113] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:13,122] {logging_mixin.py:115} INFO - [2023-06-14 14:51:13,120] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:13,122] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:13,146] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.040 seconds
[2023-06-14 14:51:23,247] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:23,250] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:23,251] {logging_mixin.py:115} INFO - [2023-06-14 14:51:23,251] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:23,261] {logging_mixin.py:115} INFO - [2023-06-14 14:51:23,259] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:23,262] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:23,286] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 14:51:33,377] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:33,379] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:33,380] {logging_mixin.py:115} INFO - [2023-06-14 14:51:33,380] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:33,391] {logging_mixin.py:115} INFO - [2023-06-14 14:51:33,390] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:33,392] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:33,419] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.048 seconds
[2023-06-14 14:51:43,522] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:43,523] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:43,525] {logging_mixin.py:115} INFO - [2023-06-14 14:51:43,524] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:43,542] {logging_mixin.py:115} INFO - [2023-06-14 14:51:43,541] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:43,543] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:43,565] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.050 seconds
[2023-06-14 14:51:53,669] {processor.py:153} INFO - Started process (PID=213) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:53,671] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:51:53,672] {logging_mixin.py:115} INFO - [2023-06-14 14:51:53,672] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:53,682] {logging_mixin.py:115} INFO - [2023-06-14 14:51:53,680] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:51:53,683] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:51:53,710] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.048 seconds
[2023-06-14 14:52:03,804] {processor.py:153} INFO - Started process (PID=218) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:03,806] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:03,808] {logging_mixin.py:115} INFO - [2023-06-14 14:52:03,807] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:03,817] {logging_mixin.py:115} INFO - [2023-06-14 14:52:03,816] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:03,818] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:03,842] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:52:13,933] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:13,935] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:13,936] {logging_mixin.py:115} INFO - [2023-06-14 14:52:13,936] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:13,947] {logging_mixin.py:115} INFO - [2023-06-14 14:52:13,945] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:13,948] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:13,973] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 14:52:24,069] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:24,071] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:24,072] {logging_mixin.py:115} INFO - [2023-06-14 14:52:24,072] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:24,081] {logging_mixin.py:115} INFO - [2023-06-14 14:52:24,080] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:24,082] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:24,106] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:52:34,195] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:34,197] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:34,199] {logging_mixin.py:115} INFO - [2023-06-14 14:52:34,199] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:34,209] {logging_mixin.py:115} INFO - [2023-06-14 14:52:34,207] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:34,210] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:34,234] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:52:44,326] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:44,328] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:44,329] {logging_mixin.py:115} INFO - [2023-06-14 14:52:44,329] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:44,339] {logging_mixin.py:115} INFO - [2023-06-14 14:52:44,337] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:44,340] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:44,369] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.051 seconds
[2023-06-14 14:52:54,465] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:54,467] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:52:54,468] {logging_mixin.py:115} INFO - [2023-06-14 14:52:54,468] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:54,478] {logging_mixin.py:115} INFO - [2023-06-14 14:52:54,476] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:52:54,479] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:52:54,501] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:53:04,607] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:04,609] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:04,610] {logging_mixin.py:115} INFO - [2023-06-14 14:53:04,610] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:04,619] {logging_mixin.py:115} INFO - [2023-06-14 14:53:04,617] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:04,621] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:04,643] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 14:53:14,741] {processor.py:153} INFO - Started process (PID=253) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:14,743] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:14,744] {logging_mixin.py:115} INFO - [2023-06-14 14:53:14,744] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:14,754] {logging_mixin.py:115} INFO - [2023-06-14 14:53:14,752] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:14,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:14,778] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:53:24,863] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:24,865] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:24,866] {logging_mixin.py:115} INFO - [2023-06-14 14:53:24,866] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:24,875] {logging_mixin.py:115} INFO - [2023-06-14 14:53:24,874] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:24,876] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:24,900] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:53:34,999] {processor.py:153} INFO - Started process (PID=263) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:35,000] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:35,001] {logging_mixin.py:115} INFO - [2023-06-14 14:53:35,001] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:35,011] {logging_mixin.py:115} INFO - [2023-06-14 14:53:35,009] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:35,012] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:35,035] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 14:53:45,134] {processor.py:153} INFO - Started process (PID=268) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:45,136] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:45,137] {logging_mixin.py:115} INFO - [2023-06-14 14:53:45,137] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:45,146] {logging_mixin.py:115} INFO - [2023-06-14 14:53:45,145] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:45,147] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:45,170] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 14:53:55,269] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:55,270] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:53:55,272] {logging_mixin.py:115} INFO - [2023-06-14 14:53:55,272] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:55,281] {logging_mixin.py:115} INFO - [2023-06-14 14:53:55,279] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:53:55,282] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:53:55,306] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 14:54:05,391] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:05,393] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:05,394] {logging_mixin.py:115} INFO - [2023-06-14 14:54:05,394] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:05,403] {logging_mixin.py:115} INFO - [2023-06-14 14:54:05,401] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:05,404] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:05,428] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 14:54:15,509] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:15,512] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:15,513] {logging_mixin.py:115} INFO - [2023-06-14 14:54:15,513] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:15,522] {logging_mixin.py:115} INFO - [2023-06-14 14:54:15,520] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:15,523] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:15,547] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 14:54:25,645] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:25,647] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:25,648] {logging_mixin.py:115} INFO - [2023-06-14 14:54:25,648] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:25,657] {logging_mixin.py:115} INFO - [2023-06-14 14:54:25,655] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:25,658] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:25,684] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:54:35,773] {processor.py:153} INFO - Started process (PID=293) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:35,775] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:35,777] {logging_mixin.py:115} INFO - [2023-06-14 14:54:35,777] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:35,786] {logging_mixin.py:115} INFO - [2023-06-14 14:54:35,785] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:35,787] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:35,813] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 14:54:45,924] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:45,926] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:45,928] {logging_mixin.py:115} INFO - [2023-06-14 14:54:45,928] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:45,937] {logging_mixin.py:115} INFO - [2023-06-14 14:54:45,935] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:45,939] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:45,963] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.047 seconds
[2023-06-14 14:54:56,030] {processor.py:153} INFO - Started process (PID=303) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:56,031] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:54:56,032] {logging_mixin.py:115} INFO - [2023-06-14 14:54:56,032] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:56,037] {logging_mixin.py:115} INFO - [2023-06-14 14:54:56,036] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:54:56,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:54:56,052] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.024 seconds
[2023-06-14 14:55:06,083] {processor.py:153} INFO - Started process (PID=308) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:06,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:06,086] {logging_mixin.py:115} INFO - [2023-06-14 14:55:06,086] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:06,093] {logging_mixin.py:115} INFO - [2023-06-14 14:55:06,092] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:06,094] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:06,111] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.031 seconds
[2023-06-14 14:55:16,167] {processor.py:153} INFO - Started process (PID=313) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:16,168] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:16,169] {logging_mixin.py:115} INFO - [2023-06-14 14:55:16,169] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:16,175] {logging_mixin.py:115} INFO - [2023-06-14 14:55:16,174] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:16,176] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:16,192] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.028 seconds
[2023-06-14 14:55:26,273] {processor.py:153} INFO - Started process (PID=318) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:26,274] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:26,276] {logging_mixin.py:115} INFO - [2023-06-14 14:55:26,276] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:26,281] {logging_mixin.py:115} INFO - [2023-06-14 14:55:26,280] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:26,282] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:26,298] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.028 seconds
[2023-06-14 14:55:36,346] {processor.py:153} INFO - Started process (PID=323) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:36,347] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:36,348] {logging_mixin.py:115} INFO - [2023-06-14 14:55:36,348] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:36,353] {logging_mixin.py:115} INFO - [2023-06-14 14:55:36,352] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:36,354] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:36,369] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.027 seconds
[2023-06-14 14:55:46,464] {processor.py:153} INFO - Started process (PID=328) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:46,465] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:46,466] {logging_mixin.py:115} INFO - [2023-06-14 14:55:46,466] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:46,471] {logging_mixin.py:115} INFO - [2023-06-14 14:55:46,470] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:46,472] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:46,488] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.029 seconds
[2023-06-14 14:55:56,520] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:56,520] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:55:56,521] {logging_mixin.py:115} INFO - [2023-06-14 14:55:56,521] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:56,525] {logging_mixin.py:115} INFO - [2023-06-14 14:55:56,524] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:55:56,526] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:55:56,539] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.023 seconds
[2023-06-14 14:56:06,590] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:06,595] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:06,596] {logging_mixin.py:115} INFO - [2023-06-14 14:56:06,596] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:06,604] {logging_mixin.py:115} INFO - [2023-06-14 14:56:06,602] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:06,607] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:06,627] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.041 seconds
[2023-06-14 14:56:16,672] {processor.py:153} INFO - Started process (PID=343) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:16,674] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:16,675] {logging_mixin.py:115} INFO - [2023-06-14 14:56:16,675] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:16,682] {logging_mixin.py:115} INFO - [2023-06-14 14:56:16,681] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:16,683] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:16,702] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.037 seconds
[2023-06-14 14:56:26,745] {processor.py:153} INFO - Started process (PID=348) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:26,746] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:26,747] {logging_mixin.py:115} INFO - [2023-06-14 14:56:26,747] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:26,754] {logging_mixin.py:115} INFO - [2023-06-14 14:56:26,753] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:26,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:26,772] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.032 seconds
[2023-06-14 14:56:36,842] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:36,844] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:36,845] {logging_mixin.py:115} INFO - [2023-06-14 14:56:36,845] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:36,853] {logging_mixin.py:115} INFO - [2023-06-14 14:56:36,851] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:36,854] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:36,873] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.038 seconds
[2023-06-14 14:56:46,959] {processor.py:153} INFO - Started process (PID=358) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:46,961] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:46,962] {logging_mixin.py:115} INFO - [2023-06-14 14:56:46,962] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:46,970] {logging_mixin.py:115} INFO - [2023-06-14 14:56:46,969] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:46,971] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:46,993] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.041 seconds
[2023-06-14 14:56:57,067] {processor.py:153} INFO - Started process (PID=363) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:57,069] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:56:57,070] {logging_mixin.py:115} INFO - [2023-06-14 14:56:57,070] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:57,079] {logging_mixin.py:115} INFO - [2023-06-14 14:56:57,077] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:56:57,080] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:56:57,102] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.041 seconds
[2023-06-14 14:57:07,194] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:07,196] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:07,198] {logging_mixin.py:115} INFO - [2023-06-14 14:57:07,198] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:07,207] {logging_mixin.py:115} INFO - [2023-06-14 14:57:07,206] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:07,208] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:07,231] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:57:17,323] {processor.py:153} INFO - Started process (PID=373) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:17,326] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:17,327] {logging_mixin.py:115} INFO - [2023-06-14 14:57:17,327] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:17,336] {logging_mixin.py:115} INFO - [2023-06-14 14:57:17,335] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:17,337] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:17,360] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.047 seconds
[2023-06-14 14:57:27,453] {processor.py:153} INFO - Started process (PID=378) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:27,455] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:27,456] {logging_mixin.py:115} INFO - [2023-06-14 14:57:27,456] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:27,466] {logging_mixin.py:115} INFO - [2023-06-14 14:57:27,464] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:27,467] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:27,489] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:57:37,571] {processor.py:153} INFO - Started process (PID=383) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:37,573] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:37,575] {logging_mixin.py:115} INFO - [2023-06-14 14:57:37,574] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:37,586] {logging_mixin.py:115} INFO - [2023-06-14 14:57:37,584] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:37,587] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:37,612] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.051 seconds
[2023-06-14 14:57:47,697] {processor.py:153} INFO - Started process (PID=388) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:47,699] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:47,700] {logging_mixin.py:115} INFO - [2023-06-14 14:57:47,700] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:47,711] {logging_mixin.py:115} INFO - [2023-06-14 14:57:47,709] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:47,712] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:47,736] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.048 seconds
[2023-06-14 14:57:57,835] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:57,837] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:57:57,838] {logging_mixin.py:115} INFO - [2023-06-14 14:57:57,838] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:57,848] {logging_mixin.py:115} INFO - [2023-06-14 14:57:57,846] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:57:57,849] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:57:57,873] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:58:07,952] {processor.py:153} INFO - Started process (PID=398) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:07,954] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:07,956] {logging_mixin.py:115} INFO - [2023-06-14 14:58:07,956] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:07,964] {logging_mixin.py:115} INFO - [2023-06-14 14:58:07,963] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:07,965] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:07,989] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 14:58:18,059] {processor.py:153} INFO - Started process (PID=403) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:18,060] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:18,062] {logging_mixin.py:115} INFO - [2023-06-14 14:58:18,062] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:18,071] {logging_mixin.py:115} INFO - [2023-06-14 14:58:18,069] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:18,073] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:18,097] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 14:58:28,174] {processor.py:153} INFO - Started process (PID=408) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:28,176] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:28,178] {logging_mixin.py:115} INFO - [2023-06-14 14:58:28,178] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:28,187] {logging_mixin.py:115} INFO - [2023-06-14 14:58:28,185] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:28,187] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:28,210] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 14:58:38,299] {processor.py:153} INFO - Started process (PID=413) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:38,302] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:38,303] {logging_mixin.py:115} INFO - [2023-06-14 14:58:38,303] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:38,312] {logging_mixin.py:115} INFO - [2023-06-14 14:58:38,310] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:38,313] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:38,338] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:58:48,417] {processor.py:153} INFO - Started process (PID=418) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:48,420] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:48,422] {logging_mixin.py:115} INFO - [2023-06-14 14:58:48,421] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:48,434] {logging_mixin.py:115} INFO - [2023-06-14 14:58:48,432] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:48,435] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:48,459] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.051 seconds
[2023-06-14 14:58:58,542] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:58,544] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:58:58,545] {logging_mixin.py:115} INFO - [2023-06-14 14:58:58,545] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:58,554] {logging_mixin.py:115} INFO - [2023-06-14 14:58:58,552] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:58:58,555] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:58:58,578] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 14:59:08,665] {processor.py:153} INFO - Started process (PID=428) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:08,668] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:08,669] {logging_mixin.py:115} INFO - [2023-06-14 14:59:08,669] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:08,679] {logging_mixin.py:115} INFO - [2023-06-14 14:59:08,677] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:08,681] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:08,703] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:59:18,790] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:18,792] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:18,792] {logging_mixin.py:115} INFO - [2023-06-14 14:59:18,792] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:18,798] {logging_mixin.py:115} INFO - [2023-06-14 14:59:18,797] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:18,799] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:18,820] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.034 seconds
[2023-06-14 14:59:28,869] {processor.py:153} INFO - Started process (PID=438) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:28,872] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:28,874] {logging_mixin.py:115} INFO - [2023-06-14 14:59:28,874] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:28,881] {logging_mixin.py:115} INFO - [2023-06-14 14:59:28,880] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:28,882] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:28,903] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.040 seconds
[2023-06-14 14:59:38,960] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:38,963] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:38,964] {logging_mixin.py:115} INFO - [2023-06-14 14:59:38,964] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:38,973] {logging_mixin.py:115} INFO - [2023-06-14 14:59:38,972] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:38,974] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:38,996] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 14:59:49,086] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:49,088] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:49,089] {logging_mixin.py:115} INFO - [2023-06-14 14:59:49,089] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:49,099] {logging_mixin.py:115} INFO - [2023-06-14 14:59:49,097] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:49,100] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:49,126] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 14:59:59,202] {processor.py:153} INFO - Started process (PID=453) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:59,204] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 14:59:59,206] {logging_mixin.py:115} INFO - [2023-06-14 14:59:59,206] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:59,215] {logging_mixin.py:115} INFO - [2023-06-14 14:59:59,213] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 14:59:59,216] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 14:59:59,240] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 15:00:09,329] {processor.py:153} INFO - Started process (PID=458) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:09,331] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:09,333] {logging_mixin.py:115} INFO - [2023-06-14 15:00:09,332] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:09,343] {logging_mixin.py:115} INFO - [2023-06-14 15:00:09,341] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:09,344] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:09,369] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.050 seconds
[2023-06-14 15:00:19,453] {processor.py:153} INFO - Started process (PID=463) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:19,455] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:19,457] {logging_mixin.py:115} INFO - [2023-06-14 15:00:19,457] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:19,468] {logging_mixin.py:115} INFO - [2023-06-14 15:00:19,466] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:19,469] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:19,493] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.047 seconds
[2023-06-14 15:00:29,531] {processor.py:153} INFO - Started process (PID=468) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:29,533] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:29,534] {logging_mixin.py:115} INFO - [2023-06-14 15:00:29,534] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:29,540] {logging_mixin.py:115} INFO - [2023-06-14 15:00:29,539] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:29,541] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:29,565] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.037 seconds
[2023-06-14 15:00:39,636] {processor.py:153} INFO - Started process (PID=473) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:39,639] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:39,640] {logging_mixin.py:115} INFO - [2023-06-14 15:00:39,640] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:39,649] {logging_mixin.py:115} INFO - [2023-06-14 15:00:39,647] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:39,650] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:39,674] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 15:00:49,760] {processor.py:153} INFO - Started process (PID=478) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:49,762] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:49,764] {logging_mixin.py:115} INFO - [2023-06-14 15:00:49,763] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:49,773] {logging_mixin.py:115} INFO - [2023-06-14 15:00:49,771] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:49,775] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:49,800] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 15:00:59,891] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:59,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:00:59,895] {logging_mixin.py:115} INFO - [2023-06-14 15:00:59,895] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:59,904] {logging_mixin.py:115} INFO - [2023-06-14 15:00:59,903] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:00:59,905] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:00:59,930] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 15:01:10,030] {processor.py:153} INFO - Started process (PID=488) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:10,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:01:10,034] {logging_mixin.py:115} INFO - [2023-06-14 15:01:10,034] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:10,043] {logging_mixin.py:115} INFO - [2023-06-14 15:01:10,041] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:01:10,044] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:10,069] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 15:01:20,153] {processor.py:153} INFO - Started process (PID=493) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:20,155] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:01:20,156] {logging_mixin.py:115} INFO - [2023-06-14 15:01:20,156] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:20,166] {logging_mixin.py:115} INFO - [2023-06-14 15:01:20,164] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:01:20,167] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:20,189] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.040 seconds
[2023-06-14 15:01:30,240] {processor.py:153} INFO - Started process (PID=498) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:30,241] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:01:30,242] {logging_mixin.py:115} INFO - [2023-06-14 15:01:30,242] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:30,249] {logging_mixin.py:115} INFO - [2023-06-14 15:01:30,248] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:01:30,250] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:30,269] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.032 seconds
[2023-06-14 15:01:40,358] {processor.py:153} INFO - Started process (PID=503) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:40,361] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:01:40,362] {logging_mixin.py:115} INFO - [2023-06-14 15:01:40,362] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:40,372] {logging_mixin.py:115} INFO - [2023-06-14 15:01:40,370] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:01:40,373] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:40,399] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.048 seconds
[2023-06-14 15:01:50,479] {processor.py:153} INFO - Started process (PID=508) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:50,481] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:01:50,483] {logging_mixin.py:115} INFO - [2023-06-14 15:01:50,482] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:50,492] {logging_mixin.py:115} INFO - [2023-06-14 15:01:50,490] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:01:50,493] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:01:50,519] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.047 seconds
[2023-06-14 15:02:00,593] {processor.py:153} INFO - Started process (PID=513) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:00,595] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:00,596] {logging_mixin.py:115} INFO - [2023-06-14 15:02:00,596] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:00,603] {logging_mixin.py:115} INFO - [2023-06-14 15:02:00,602] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:00,604] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:00,625] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.037 seconds
[2023-06-14 15:02:10,722] {processor.py:153} INFO - Started process (PID=518) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:10,724] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:10,726] {logging_mixin.py:115} INFO - [2023-06-14 15:02:10,726] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:10,736] {logging_mixin.py:115} INFO - [2023-06-14 15:02:10,734] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:10,737] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:10,761] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 15:02:20,836] {processor.py:153} INFO - Started process (PID=523) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:20,839] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:20,840] {logging_mixin.py:115} INFO - [2023-06-14 15:02:20,840] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:20,849] {logging_mixin.py:115} INFO - [2023-06-14 15:02:20,848] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:20,850] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:20,874] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 15:02:30,933] {processor.py:153} INFO - Started process (PID=528) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:30,934] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:30,935] {logging_mixin.py:115} INFO - [2023-06-14 15:02:30,935] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:30,942] {logging_mixin.py:115} INFO - [2023-06-14 15:02:30,941] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:30,943] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:30,962] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.033 seconds
[2023-06-14 15:02:41,028] {processor.py:153} INFO - Started process (PID=533) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:41,029] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:41,030] {logging_mixin.py:115} INFO - [2023-06-14 15:02:41,030] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:41,037] {logging_mixin.py:115} INFO - [2023-06-14 15:02:41,035] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:41,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:41,056] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.033 seconds
[2023-06-14 15:02:51,130] {processor.py:153} INFO - Started process (PID=538) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:51,132] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:02:51,133] {logging_mixin.py:115} INFO - [2023-06-14 15:02:51,133] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:51,143] {logging_mixin.py:115} INFO - [2023-06-14 15:02:51,141] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:02:51,144] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:02:51,167] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 15:03:01,238] {processor.py:153} INFO - Started process (PID=543) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:01,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:01,241] {logging_mixin.py:115} INFO - [2023-06-14 15:03:01,241] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:01,249] {logging_mixin.py:115} INFO - [2023-06-14 15:03:01,247] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:01,250] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:01,269] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.035 seconds
[2023-06-14 15:03:11,347] {processor.py:153} INFO - Started process (PID=548) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:11,349] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:11,351] {logging_mixin.py:115} INFO - [2023-06-14 15:03:11,351] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:11,359] {logging_mixin.py:115} INFO - [2023-06-14 15:03:11,357] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:11,360] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:11,381] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.039 seconds
[2023-06-14 15:03:21,472] {processor.py:153} INFO - Started process (PID=553) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:21,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:21,474] {logging_mixin.py:115} INFO - [2023-06-14 15:03:21,474] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:21,484] {logging_mixin.py:115} INFO - [2023-06-14 15:03:21,482] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:21,485] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:21,508] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 15:03:31,613] {processor.py:153} INFO - Started process (PID=558) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:31,615] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:31,616] {logging_mixin.py:115} INFO - [2023-06-14 15:03:31,616] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:31,625] {logging_mixin.py:115} INFO - [2023-06-14 15:03:31,624] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:31,627] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:31,649] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.042 seconds
[2023-06-14 15:03:41,741] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:41,744] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:41,745] {logging_mixin.py:115} INFO - [2023-06-14 15:03:41,745] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:41,755] {logging_mixin.py:115} INFO - [2023-06-14 15:03:41,753] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:41,756] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:41,778] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 15:03:51,879] {processor.py:153} INFO - Started process (PID=568) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:51,881] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:03:51,882] {logging_mixin.py:115} INFO - [2023-06-14 15:03:51,882] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:51,891] {logging_mixin.py:115} INFO - [2023-06-14 15:03:51,889] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:03:51,892] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:03:51,917] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.045 seconds
[2023-06-14 15:04:02,014] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:02,016] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:02,017] {logging_mixin.py:115} INFO - [2023-06-14 15:04:02,017] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:02,027] {logging_mixin.py:115} INFO - [2023-06-14 15:04:02,025] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:02,028] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:02,053] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.046 seconds
[2023-06-14 15:04:12,132] {processor.py:153} INFO - Started process (PID=578) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:12,133] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:12,134] {logging_mixin.py:115} INFO - [2023-06-14 15:04:12,134] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:12,141] {logging_mixin.py:115} INFO - [2023-06-14 15:04:12,140] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:12,142] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:12,166] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.038 seconds
[2023-06-14 15:04:22,259] {processor.py:153} INFO - Started process (PID=583) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:22,261] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:22,263] {logging_mixin.py:115} INFO - [2023-06-14 15:04:22,263] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:22,272] {logging_mixin.py:115} INFO - [2023-06-14 15:04:22,270] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:22,273] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:22,297] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
[2023-06-14 15:04:32,397] {processor.py:153} INFO - Started process (PID=588) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:32,398] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:32,400] {logging_mixin.py:115} INFO - [2023-06-14 15:04:32,400] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:32,409] {logging_mixin.py:115} INFO - [2023-06-14 15:04:32,407] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:32,410] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:32,434] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.043 seconds
[2023-06-14 15:04:42,527] {processor.py:153} INFO - Started process (PID=593) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:42,529] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:42,531] {logging_mixin.py:115} INFO - [2023-06-14 15:04:42,531] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:42,541] {logging_mixin.py:115} INFO - [2023-06-14 15:04:42,539] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:42,543] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:42,569] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.049 seconds
[2023-06-14 15:04:52,639] {processor.py:153} INFO - Started process (PID=598) to work on /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:52,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/API_ETL.py for tasks to queue
[2023-06-14 15:04:52,642] {logging_mixin.py:115} INFO - [2023-06-14 15:04:52,642] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:52,652] {logging_mixin.py:115} INFO - [2023-06-14 15:04:52,650] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/API_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_ETL.py", line 13, in <module>
    from pytrends import exceptions
ModuleNotFoundError: No module named 'pytrends'
[2023-06-14 15:04:52,653] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/API_ETL.py
[2023-06-14 15:04:52,678] {processor.py:161} INFO - Processing /opt/airflow/dags/API_ETL.py took 0.044 seconds
