[2023-07-01 15:57:16,493] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.cargar_data manual__2023-07-01T15:46:05.786068+00:00 [queued]>
[2023-07-01 15:57:16,500] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.cargar_data manual__2023-07-01T15:46:05.786068+00:00 [queued]>
[2023-07-01 15:57:16,500] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-01 15:57:16,501] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2023-07-01 15:57:16,501] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-01 15:57:16,510] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-07-01 15:46:05.786068+00:00
[2023-07-01 15:57:16,514] {standard_task_runner.py:52} INFO - Started process 230 to run task
[2023-07-01 15:57:16,518] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'cargar_data', 'manual__2023-07-01T15:46:05.786068+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmp3fd5yham', '--error-file', '/tmp/tmptws493tz']
[2023-07-01 15:57:16,520] {standard_task_runner.py:80} INFO - Job 10: Subtask cargar_data
[2023-07-01 15:57:16,588] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.cargar_data manual__2023-07-01T15:46:05.786068+00:00 [running]> on host c8adaca8488b
[2023-07-01 15:57:16,628] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-01 15:57:16,665] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-01T15:46:05.786068+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-01T15:46:05.786068+00:00
[2023-07-01 15:57:16,667] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-07-01 15
[2023-07-01 15:57:16,672] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/API_ETL.py", line 107, in cargar_data
    date.month)+'-'+str(date.day)+'-'+str(date.hour)+".csv", mode='a')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: read_csv() got an unexpected keyword argument 'mode'
[2023-07-01 15:57:16,685] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=API_ETL, task_id=cargar_data, execution_date=20230701T154605, start_date=20230701T155716, end_date=20230701T155716
[2023-07-01 15:57:16,692] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task cargar_data (read_csv() got an unexpected keyword argument 'mode'; 230)
[2023-07-01 15:57:16,730] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-01 15:57:16,760] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
